version: '3.7'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: server.settings
      DEBUG: "True"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    depends_on:
      - db
    networks:
      - project
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - project

networks:
  project:       
