# Generated by Django 4.2.6 on 2024-04-04 14:10

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='curses',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='languages',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='experience',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='skills',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
    ]
