# Generated by Django 4.2.6 on 2024-04-04 14:23

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdata_curses_alter_userdata_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='contact_email',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='contact_telegram',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='curses',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='graduation_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='languages',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='lastname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='surname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='experience',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='skills',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
    ]
