# Generated by Django 4.2.6 on 2024-04-04 17:06

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdata_additional_info_alter_userdata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='experience',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
    ]
