# Generated by Django 4.2.6 on 2024-04-05 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('font', models.CharField()),
                ('size', models.FloatField()),
                ('color', models.CharField()),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('coordinate_z', models.IntegerField()),
                ('transparency', models.FloatField()),
                ('italics', models.BooleanField(default=False)),
                ('bold', models.BooleanField(default=True)),
                ('underlining', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('font', models.CharField()),
                ('size', models.FloatField()),
                ('color', models.CharField()),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('coordinate_z', models.IntegerField()),
                ('transparency', models.FloatField()),
                ('italics', models.BooleanField(default=True)),
                ('bold', models.BooleanField(default=False)),
                ('underlining', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('font', models.CharField()),
                ('size', models.FloatField()),
                ('color', models.CharField()),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('coordinate_z', models.IntegerField()),
                ('transparency', models.FloatField()),
                ('italics', models.BooleanField(default=True)),
                ('bold', models.BooleanField(default=False)),
                ('underlining', models.BooleanField(default=True)),
                ('list_values', django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('font_list', models.CharField()),
                ('size_list', models.FloatField()),
                ('color_list', models.CharField()),
                ('transparency_list', models.FloatField()),
                ('italics_list', models.BooleanField(default=True)),
                ('bold_list', models.BooleanField(default=False)),
                ('underlining_list', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('coordinate_z', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='portfolio_photo/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('coordinate_z', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('pictures', django_jsonform.models.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='portfolio_slider/'), blank=True, null=True, size=None)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('font', models.CharField()),
                ('size', models.FloatField()),
                ('color', models.CharField()),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('coordinate_z', models.IntegerField()),
                ('transparency', models.FloatField()),
                ('italics', models.BooleanField(default=False)),
                ('bold', models.BooleanField(default=True)),
                ('underlining', models.BooleanField(default=False)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('border', models.BooleanField(default=False)),
                ('border_color', models.CharField(blank=True, null=True)),
                ('border_transparency', models.FloatField(blank=True, null=True)),
                ('border_radius', models.FloatField(blank=True, null=True)),
                ('border_width', models.FloatField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('heading_ids', models.ManyToManyField(related_name='porfolio_headings', to='user.heading')),
                ('link_ids', models.ManyToManyField(related_name='porfolio_links', to='user.link')),
                ('list_ids', models.ManyToManyField(related_name='porfolio_lists', to='user.list')),
                ('photo_ids', models.ManyToManyField(related_name='porfolio_photos', to='user.photo')),
                ('slider_ids', models.ManyToManyField(related_name='porfolio_sliders', to='user.slider')),
                ('textfield_ids', models.ManyToManyField(related_name='porfolio_textfields', to='user.textfield')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
