# Generated by Django 4.2.6 on 2024-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_heading_link_list_photo_slider_textfield_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='heading_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='porfolio_headings', to='user.heading'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='porfolio_links', to='user.link'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='list_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='porfolio_lists', to='user.list'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='porfolio_photos', to='user.photo'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slider_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='porfolio_sliders', to='user.slider'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='textfield_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='porfolio_textfields', to='user.textfield'),
        ),
    ]
