# Generated by Django 4.2.6 on 2024-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_hashtag_sphere_portfolio_hashtag_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='education_level',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='experience_years',
            field=models.CharField(blank=True, null=True),
        ),
    ]
