# Generated by Django 4.2.6 on 2024-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_portfolio_portfolio_html_portfolio_portfolio_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='contact_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='contact_telegram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
