# Generated by Django 4.2.6 on 2024-04-09 10:46

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userdata_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='languages',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True), blank=True, null=True, size=None),
        ),
    ]
