# Generated by Django 4.2.6 on 2024-04-10 15:25

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_userdata_curses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='curses',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='languages',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
