# Generated by Django 4.2.6 on 2024-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_userexperience_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperience',
            name='experience',
        ),
        migrations.AddField(
            model_name='userexperience',
            name='experience_info',
            field=models.CharField(blank=True, null=True),
        ),
    ]
