# Generated by Django 4.2.6 on 2024-05-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_uservacancy_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfield',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='coordinate_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='coordinate_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='coordinate_z',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='font',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='transparency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
