# Generated by Django 4.2.6 on 2024-05-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_textfield_text_alter_textfield_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservacancy',
            name='user_id',
        ),
        migrations.AddField(
            model_name='uservacancy',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
