# Generated by Django 4.2.6 on 2024-05-03 18:08

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_uservacancy_user_id_uservacancy_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='pictures',
            field=django_jsonform.models.fields.ArrayField(base_field=models.ImageField(upload_to='portfolio_slider/'), blank=True, null=True, size=None),
        ),
    ]
