# Generated by Django 4.2.6 on 2024-05-03 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_slider_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='pictures',
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='portfolio_slider/')),
                ('slider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='user.slider')),
            ],
        ),
    ]
