# Generated by Django 4.2.6 on 2024-05-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_slider_pictures_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='heading_ids',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link_ids',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='list_ids',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_ids',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='slider_ids',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='textfield_ids',
        ),
        migrations.AddField(
            model_name='photo',
            name='portfolio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.portfolio'),
        ),
        migrations.AddField(
            model_name='slider',
            name='portfolio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.portfolio'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='portfolio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.portfolio'),
        ),
    ]
