# Generated by Django 4.2.6 on 2024-05-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_portfolio_heading_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='border_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='coordinate_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='coordinate_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='border_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='coordinate_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='coordinate_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskills',
            name='border_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskills',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskills',
            name='coordinate_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskills',
            name='coordinate_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskills',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskills',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
