# Generated by Django 4.2.6 on 2024-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_userdata_city_alter_userdata_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_text',
            field=models.TextField(default=''),
        ),
    ]
